### PR TITLE
Better docs

### LINKED ISSUE #10: Render markdown for JSDoc
JSDoc can contain markdown snippets with example. They should be rendered accordingly. It will require to pre-parse and clean JSDoc in Rust to get rid of comment markers (`*`). Note to self: whitespaces should be preserved.

### PR DESCRIPTION
**Pull request by lucacasonato**
Added JSDoc Markdown and Code Syntax Highlighting.

Ref #8 and closes #10

### CODE REVIEW

**Comment by bartlomieju** [comment]
Nice! I get some errors in console, but I guess they're not terminal.

**Comment by bartlomieju** [comment]
@lucacasonato I just pushed `master` with JSDoc stripping in Rust. There is still some quirks with whitespaces, but it will strip all comment markers.

**Comment by bartlomieju** [comment]
@lucacasonato please merge `master` again, fixed tests and made sure proper amount of whitespace is removed from JSdocs

**Comment by bartlomieju** [comment]
@lucacasonato ready to merge?

**Comment by lucacasonato** [comment]
Sure, I'll do more in followup PRs

**Pull request merged**
