### PR TITLE
NextJS + design changes

### PR DESCRIPTION
**Pull request by lucacasonato**
Moved to NextJS for hybrid side rendering + updated design + added index page.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@lucacasonato I cannot deploy this branch anymore

**Comment by lucacasonato** [comment]
Correct. Could you change the settings on now to have the root path field be empty and change the template from 'Create React App' to 'Next JS'. Then it should work again.

**Comment by bartlomieju** [comment]
Cool, deployed, but I get this:
Screenshot 2020-03-31 at 10 49 31


Anyway, land when you think it's ready

**Comment by lucacasonato** [comment]
> Cool, deployed, but I get this:
> Screenshot 2020-03-31 at 10 49 31
> 
> Anyway, looks great, land when you think it's ready

Yup - `deno doc` does not support re exports yet, so two of the example links are just empty... I'll see if I manage to add re-exports to deno today. You can see some content with this link: https://deno-doc-git-fork-luca-rand-nextjs.bartlomieju.now.sh/deno.land/std/fs/copy.ts

**Comment by bartlomieju** [comment]
> > Cool, deployed, but I get this:
> > Screenshot 2020-03-31 at 10 49 31
> > Anyway, looks great, land when you think it's ready
> 
> Yup - `deno doc` does not support re exports yet, so two of the example links are just empty... I'll see if I manage to add re-exports to deno today. You can see some content with this link: https://deno-doc-git-fork-luca-rand-nextjs.bartlomieju.now.sh/deno.land/std/fs/copy.ts

I see, I changed URL to `http/server.ts` and can see docs now :+1: 

Nice mobile output 👍

**Pull request merged**
